// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDekjTDTL636V02JLswPFsGj9bQcKdj_8E',
    appId: '1:954873531504:web:fb8fa4bac68efebbfcf8b5',
    messagingSenderId: '954873531504',
    projectId: 'parla-italiano-bf214',
    authDomain: 'parla-italiano-bf214.firebaseapp.com',
    storageBucket: 'parla-italiano-bf214.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHNNCNDGZqDFx2wEQBGJhwI3_YjU2PWFQ',
    appId: '1:954873531504:android:dcde48727ee54402fcf8b5',
    messagingSenderId: '954873531504',
    projectId: 'parla-italiano-bf214',
    storageBucket: 'parla-italiano-bf214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ffId1DyPq3b27KotFZ6IzZ-MHv2anRc',
    appId: '1:954873531504:ios:3aa2ff3c613c96fafcf8b5',
    messagingSenderId: '954873531504',
    projectId: 'parla-italiano-bf214',
    storageBucket: 'parla-italiano-bf214.appspot.com',
    iosBundleId: 'com.example.parlaItaliano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ffId1DyPq3b27KotFZ6IzZ-MHv2anRc',
    appId: '1:954873531504:ios:764f6ec0ba700c73fcf8b5',
    messagingSenderId: '954873531504',
    projectId: 'parla-italiano-bf214',
    storageBucket: 'parla-italiano-bf214.appspot.com',
    iosBundleId: 'com.example.parlaItaliano.RunnerTests',
  );
}
